from collections.abc import Iterable
from typing import Protocol

from app.modules.posts.domain.sync import PostEmbeddingRecord


class PostSyncRepository(Protocol):
    async def fetch_content_hashes(self, ids: Iterable[str]) -> dict[str, str]: ...
    async def upsert_embeddings(self, records: list[PostEmbeddingRecord]) -> None: ...
    async def deactivate_embedding(self, post_id: str, source_version: int) -> None: ...
    async def get_checkpoint(self, consumer: str) -> int: ...
    async def save_checkpoint(self, consumer: str, event_id: int) -> None: ...
