from collections.abc import Iterable
from typing import Protocol

from app.modules.posts.domain.profiles import UserInterestState


class UserProfileRepository(Protocol):
    async def get_post_embeddings(self, post_ids: Iterable[str]) -> dict[str, list[float]]: ...
    async def get_states(self, user_ids: Iterable[str]) -> dict[str, UserInterestState]: ...
    async def save_states(self, states: list[UserInterestState], profile_version: str) -> None: ...
    async def get_checkpoint(self, consumer: str) -> int: ...
    async def save_checkpoint(self, consumer: str, event_id: int) -> None: ...
    async def reset_profiles(self, user_id: str | None = None) -> None: ...
    async def reset_checkpoint(self, consumer: str) -> None: ...
